version: "3"

services:
  app:
    image: receipt-analysis
    container_name: receipt-analysis
    ports: 
    - 80:80
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
    - ./app:/app/
    - ~/.aws:/root/.aws:ro
    - ~/.passwd-s3fs:/root/.passwd-s3fs:ro